name: Create Branch from Issue Assignment

on:
  issues:
    types:
      - assigned

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create branch from issue
        env:
          SOURCE_BRANCH: main
        run: |

          # Configure git with the GitHub token
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git config credential.helper "store --file=.git-credentials"
          echo "https://github.com:${{ secrets.TOKEN }}" > .git-credentials

          # Extract the issue number and assignee from the JSON payload
          ISSUE_TITLE=$(jq --raw-output .issue.title "$GITHUB_EVENT_PATH")
          ISSUE_NUMBER=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          ASSIGNee=$(jq --raw-output .issue.assignee.login "$GITHUB_EVENT_PATH")
          BRANCH_NAME=$(echo "$ISSUE_NUMBER$ISSUE_TITLE")
          new_branch_name=$(echo "$branch_name" | sed 's/[][BUG]//g')
          new_branch_name=$(echo "$new_branch_name" | sed -e "s/ /-/g")

          # Create a new branch using the assigned issue number
          git checkout -b "$new_branch_name" "$SOURCE_BRANCH"
          git push origin "$NEW_BRANCH"
