name: Create Branch from Issue Assignment

on:
  issues:
    types:
      - assigned

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create branch from issue
        env:
          SOURCE_BRANCH: main
        run: |

          # Configure git with the GitHub token
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git config credential.helper "store --file=.git-credentials"
          echo "https://github.com:${{ secrets.TOKEN }}" > .git-credentials
          
          # Extract the issue number and assignee from the JSON payload
          ISSUE_NUMBER=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          ASSIGNee=$(jq --raw-output .issue.assignee.login "$GITHUB_EVENT_PATH")

          # Check if there's a specific source branch in the .config file
          if [ -f .config ]; then
            SOURCE_BRANCH=$(cat .config)
          fi

          # Create a new branch using the assigned issue number
          NEW_BRANCH="issue-${ISSUE_NUMBER}-assigned-to-${ASSIGNee}"
          git checkout -b "$NEW_BRANCH" "$SOURCE_BRANCH"
          git push origin "$NEW_BRANCH"
