name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV
        
      - name: Release ISO File
        uses: ncipollo/release-action@v1
        with:
            artifacts: "*.tar.gz"
            body: "v2.0.0"
            generateReleaseNotes: false
            name: "TCET-Linux"
            tag: ${{ env.DATE }}
            